### ISSUE TITLE
S1GPS - Infografía Gestión de Software

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Yabin-2021#2]
[Infografia Conceptos y Fases de Gestión de Proyectos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Yabin-2021/files/9419035/Infografia.Conceptos.y.Fases.de.Gestion.de.Proyectos.pdf)

**Comment by CxrlosMX** [comment]
Excelente trabajo, calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
